# ARM(Abstract Reasoning Model) 아키텍처 설정 (Mini Ver.)
name: arm.arm_v1@ARM
loss:
  name: losses@ARMLossHead 
  loss_type: stablemax_cross_entropy

# ACT (Adaptive Computation Time) 관련 설정은 유지합니다.
halt_exploration_prob: 0.1
halt_max_steps: 16

# --- ARM 고유 파라미터 ---
initial_modules: 1 # 시작 시 추론 모듈의 개수
max_modules: 8     # 최대 추론 모듈의 개수
inner_loops: 4 # 활성 모듈의 내부 반복 추론 횟수

# --- 새로운 성장 메커니즘을 위한 하이퍼파라미터 ---
convergence_check_interval: 1000 # 수렴 상태를 확인할 주기 (훈련 스텝 단위)
stable_threshold: 1.0e-5         # 그래디언트 분산이 이 값보다 낮으면 수렴으로 판단
rate_hardprob: 0.15              # 상위 15%의 문제를 난제로 정의
forced_allocation_duration: 1000 # 새 모듈 추가 후 난제를 강제 할당할 기간 (훈련 스텝 단위)

# --- Transformer 파라미터 (Mini 버전에 맞게 축소) ---
reasoning_layers: 1 # 각 추론 모듈 내부의 트랜스포머 레이어 수
hidden_size: 128    # 256 -> 128 로 축소
num_heads: 4        # 8 -> 4 로 축소
expansion: 4
pos_encodings: rope
